### ISSUE TITLE
Tables do not work in FBReader for desktop

### ISSUE THREAD

**Issue by dismine** [slonopotamus/asciidoctor-fb2#17]
Hi.

In my document I have a table.

```
[cols="11*^.^m"]
.Абсолютные величины размерных признаков типовых фигур женщин 2-й полнотной группы, *обхваты груди 84-104 см*.
|===

.4+h|Номер размерного признака .4+h|Размерные признаки .4+h|Условные обозначения размерных признаков 6+h|Обхват груди 2.3+h|Разность размерных признаков между смежными

h|84 h|88 h|92 h|96 h|100 h|104

6+h|Обхват бедер

h|92 h|96 h|100 h|104 h|108 h|112 h|размерами h|ростами

e|1 e|2 e|3 e|4 e|5 e|6 e|7 e|8 e|9 e|10 e|11

|1|Рост|Р|158|158|158|158|158|158|0|6,0

|7|Высота линии талии|Влт|98,4|98,6|98,8|99,0|99,2|99,4|0,2|4,2

|16|Полуобхват груди третий|Сг III|42,0|44,0|46,0|48,0|50,0|52,0|2,0|0
|35|Высота груди|Вг|32,7|33,6|34,5|35,4|36,3|37,2|0,9|0,1

|=== 
```

**Comment by slonopotamus** [comment]
Hmm... But it *does* work. This is a screenshot from [Calibre](https://calibre-ebook.com/):

![image](https://user-images.githubusercontent.com/92637/100114680-bb6c5f80-2e82-11eb-90cf-bf961a275138.png)

Same table in [AsciiDoc plugin for IntelliJ IDEA](https://plugins.jetbrains.com/plugin/7391-asciidoc):

![image](https://user-images.githubusercontent.com/92637/100114863-ece52b00-2e82-11eb-903a-bc41869d35e4.png)

Okay, asciidoctor-fb2 is missing table title. But table itself is there.

**Comment by dismine** [comment]
In my case Calibre cannot open my document.
```
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/utils/ipc/simple_worker.py", line 284, in main
    res = {'result':func(*args, **kwargs)}
  File "/usr/lib/calibre/calibre/ebooks/oeb/iterator/book.py", line 65, in extract_book
    plumber.opts, plumber.input_fmt, log, {}, tdir)
  File "/usr/lib/calibre/calibre/customize/conversion.py", line 245, in __call__
    log, accelerators)
  File "/usr/lib/calibre/calibre/ebooks/conversion/plugins/fb2_input.py", line 86, in convert
    self.extract_embedded_content(doc)
  File "/usr/lib/calibre/calibre/ebooks/conversion/plugins/fb2_input.py", line 174, in extract_embedded_content
    with open(fname, 'wb') as f:
IOError: [Errno 2] There is no such file or directory: 'images/03-publisher.png'
```
This is what I see in FBReader
![fbreader](https://user-images.githubusercontent.com/6575331/100115785-9c1e0400-2e7b-11eb-96cf-c17dba26939e.png)

And Okular doesn't see it at all. Content of the table is missing.

**Comment by slonopotamus** [comment]
> IOError: [Errno 2] There is no such file or directory: 'images/03-publisher.png'

This is a different problem, something is not working with images.

**Comment by slonopotamus** [comment]
@dismine could you please try Calibre again with asciidoctor-fb2 v0.2.4?

**Comment by dismine** [comment]
Works, but only in Calibre.

![table](https://user-images.githubusercontent.com/6575331/100130149-09856100-2e8b-11eb-8347-d1104a39764b.png)

**Comment by slonopotamus** [comment]
WRT Okular: it simply [doesn't support](https://github.com/KDE/okular/blob/v20.11.80/generators/fictionbook/converter.cpp#L394-L431) neither `<table>` nor `<subtitle>`.

**Comment by slonopotamus** [comment]
FBReader also doesn't support tables: https://github.com/geometer/FBReader/issues/156

Besides that, FBReader for desktop is abandoned, last commit was done in 2016.

So, I don't think we can do here anything else.

**Comment by slonopotamus** [comment]
I've created a PR for Okular with initial tables support: https://invent.kde.org/graphics/okular/-/merge_requests/325
